{
    "name": "Real Estate",
    "summary": "Real estate advertising module for learning purposes, following the tutorial at Odoo documentation.",
    "author": "Vauxoo",
    "license": "LGPL-3",
    "website": "https://www.vauxoo.com/",
    "category": "Customizations",
    "version": "19.0.1.0.0",
    "depends": ["base"],
    "data": [
        "security/ir.model.access.csv",
        "views/estate_property_offer_views.xml",
        "views/estate_property_type_views.xml",
        "views/estate_property_tag_views.xml",
        "views/estate_property_views.xml",
        "views/res_users_views.xml",
        "views/estate_menus.xml",
        "data/estate.property.type.csv",
        "demo/demo_data.xml",
    ],
    "application": True,
}
